
version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_prod2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: eap_it33_prod_db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

volumes:
  pgdata_prod:
