name: Deploy PostgreSQL Docker Compose

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod

jobs:

  checkout_and_transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy project to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "./infra/docker/docker-compose.prod2.yml"
          target: "/home/${{ secrets.VPS_USER }}/"

      # Move file into /opt using sudo
      - name: Move file to /opt (requires sudo)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            sudo mv /home/${{ secrets.VPS_USER }}/infra/docker/docker-compose.prod2.yml /opt/postgres/
            sudo chown -R $USER:$USER /opt/postgres

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    needs: checkout_and_transfer

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd /opt/postgres
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            docker compose -p prod-test -f docker-compose.prod2.yml up -d
            echo "Deployment complete"