name: View Docker Logs

on:
  workflow_dispatch:
    inputs:
      container_name:
        description: "Docker container name"
        required: true
        default: eap-frontend-dev
        type: choice
        options: 
          - eap-frontend-test
          - eap-frontend-prod
          - eap-backend-dev
          - eap-backend-test
          - eap-backend-prod

jobs:
  view_logs:
    runs-on: ubuntu-latest

    steps:
      - name: View container logs via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |

            echo "===== CONTAINER STATUS ====="
            docker ps -a | grep ${{ github.event.inputs.container_name }} || true

            echo "===== Start Container ====="
            docker start ${{ github.event.inputs.container_name }}